version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      prod-dependencies:
        dependency-type: production
      dev-dependencies:
        dependency-type: development
