services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - "127.0.0.1:8000:8000"

  dynamodb-init:
    image: hashicorp/terraform:1.9
    depends_on:
      - dynamodb
    restart: on-failure
    volumes:
      - type: bind
        source: ./db-schemas/dynamodb
        target: /infra
    working_dir: /infra
    entrypoint: "/bin/sh"
    command: ["-c", "terraform init && terraform apply -auto-approve"]
    environment:
      TF_VAR_endpoint: http://dynamodb:8000
      TF_VAR_region: us-west-2
      TF_VAR_access_key_id: xxx
      TF_VAR_secret_access_key: xxx

  mysql:
    image: mysql:8.4
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xxx
    command: ["--general-log=1", "--general-log-file=/tmp/query.log"]

  mysql-init:
    image: flyway/flyway:11-alpine
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - type: bind
        source: ./db-schemas/mysql
        target: /flyway/sql
    command:
      - "-url=jdbc:mysql://mysql:3306/blog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true"
      - "-user=root"
      - "-password=xxx"
      - "-connectRetries=60"
      - "migrate"

  ftp:
    image: delfer/alpine-ftp-server
    restart: always
    ports:
      - "127.0.0.1:2121:21"
      - "127.0.0.1:21000-21010:21000-21010"
    environment:
      ADDRESS: "localhost"
      USERS: "foo|BC499D13-EB4B-4EAE-994D-7435364654C5"

  sftp:
    image: atmoz/sftp:alpine
    restart: always
    ports:
      - "127.0.0.1:2222:22"
    command:
      - "foo:bar:1000:1000:upload"
