name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Update version
        id: update-version
        run: |
          version=${{ github.event.release.tag_name }}
          npm version "${version/v/}" --git-tag-version false --ws

          if echo "$version" | grep -qE '^[0-9.]+$'; then
            echo "is-dev=0" >> $GITHUB_OUTPUT
          else
            echo "is-dev=1" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: npm run build

      - name: Login NPM
        run: npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}"

      - name: Publish packages
        if: ${{ steps.update-version.outputs.is-dev == '0' }}
        run: npm publish -ws --access public

      - name: Publish dev packages
        if: ${{ steps.update-version.outputs.is-dev == '1' }}
        run: npm publish -ws --access public --tag dev
